# -*- coding: utf-8 -*-
"""Zoo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qd_v_rCo7LXxb9yMswhG39ARrfDpPhq4
"""

def hours():
 print('Open 9-5 daily')